package com.jbc.util.model;

public enum EmployeeProfessionUtil {

	JAVA, DEV_OPS, REACT, SQL, SUPPORT_SPECIALIST, IT_TECHNICIAN, SYSTEM_ANALYST, CHIEF_HR_OFFICER, EMPLOYMENT_MANAGER,
	EXECUTIVE_RECRUITER;

}
